version: '3.1'

services:
  postgres:
    image: postgres:12.6
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.1
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
            - postgres

  qcoder:
    build: qcoder/.
    env_file:
      - .env
    volumes:
      - ./qcoder/qcoder_app:/home/qcoder_app
    ports:
      - "8000:8000"
    command:
      ["./run_app.sh"]
    depends_on:
      - postgres
